[package]
name = "try-rs"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
ratatui = "0.29"
crossterm = "0.29.0"
dirs = "6.0.0"
fuzzy-matcher = "0.3"
chrono = "0.4"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
